services:
  - type: web
    name: holonic-ai-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: holonic_ai_db
          property: connectionString

databases:
  - name: holonic_ai_db
    databaseName: holonic_ai
    user: holonic_ai_user